function uc_sample = run_UC(str , state , demandScenario , windScenario, line_status, params)
uc_sample.windScenario = windScenario;
uc_sample.demandScenario = demandScenario;
uc_sample.line_status = line_status;
params.windScenario = windScenario;
params.demandScenario = demandScenario;
params.line_status = line_status;
[Pg,objective,onoff,y,demandVector,success,windSpilled,loadLost] = generalSCUC(str,params,state,[]);
uc_sample.success = success;
uc_sample.onoff = onoff;
uc_sample.objective = objective;
uc_sample.Pg = Pg;
uc_sample.windSpilled = windSpilled;
uc_sample.loadLost = loadLost;
uc_sample.voltage_setpoints = [];
